#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    N = int(input())
if (N in range(2,6) and N%2==0) or(N>20 and N%2==0):
    print("Not Weird")
elif (N in range(6,21)and N%2==0) or N%2==1:
    print("Weird")
